name: Run Tests

on:
  push:
    branches:
      - feature/*  # Run tests on all feature branches
      - dev        # Run tests when pushing to the 'dev' branch
      - main       # Run tests when pushing to the 'main' branch
  pull_request:
    branches:
      - dev        # Run tests when creating a pull request to 'dev'
      - main       # Run tests when creating a pull request to 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover
